baseURL = "https://docs.bfportal.gg/"
languageCode = 'en-us'
theme = "hugo-geekdoc"
title = "Portal Documentation"

titleCaseStyle = "Go"
[outputs]
    home = ["HTML", "RSS"]

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"


[[module.mounts]]
source = "../docs/"
target = "./content/"
excludeFiles = ["portal_blocks/**"]

[[module.mounts]]
source = "../docs/portal_blocks/blocks"
target = "./content/blocks"


[params]
    geekdocLogo= "/images/bf_portal_logo_bc.png"
